### PR TITLE
feat(step_definition): Allows to define step function without return.

### PR DESCRIPTION
**Pull request by titouanfreville**
Issue: It is not possible to use function without return when
       matching steps, resulting in a lot of Nil only error
       returns.

Fix: Allows to provide empty result function by correctly matching
     reflect Calls on step Handler.
     When nothing is returned by the Handler, it will return
     nil as if errors was nil.

### CODE REVIEW

**Comment by titouanfreville** [comment]
Last commit add `goconvey` dependencies to simplify some unit test writting on Panics. 

It can be rollbacked or adapt to keep the tests with a custom system if dependencies should not be added.

**Comment by mattwynne** [comment]
This needs re-basing before it can be merged. @vearutop could you help?

**Review by vearutop — APPROVED** [review]

**Comment by vearutop** [comment]
Let's wait for @titouanfreville response for couple more days, otherwise this PR looks good to me to merge.

**Comment by mattwynne** [comment]
I suggest updating the CHANGELOG as part of the PR, it's a good idea so you don't forget to do it after the merge.

**Comment by titouanfreville** [comment]
If there are no conflict, it should be ok to merge it. 

I also used it to start a discution arround test tools but did not get any feedback on it.

I'll update the changelog ASAP before merging :)

**Comment by vearutop** [comment]
I'm not opposed to new testing tools (since it does not affect end-user much) if they help writing more reliable and readable tests, though not sure if goconvey brings better ergonomics compared to `testify` or `testing` that are already in use.

**Comment by vearutop** [comment]
Seems @titouanfreville is busy, so I updated README and CHANGELOG and going to merge this PR. If any additional changes are necessary, let's deliver them in a separate PR.

**Pull request merged**
