### PR TITLE
docs: Add link to Slack community

### PR DESCRIPTION
**Pull request by smikulcik**
Closes https://github.com/cucumber/godog/issues/203

Just adds a link in the readme to the slack

### CODE REVIEW

**Comment by smikulcik** [comment]
the travis file is bad... #209 must go in first

**Comment by jaysonesmith** [comment]
Hey again @smikulcik! Thank you for this change! Given that the project is under Cucumber now, it makes sense that we should reuse the space we've already got available to us: Slack. Could you update your change to point here instead please? Join link: `https://cucumberbdd-slack-invite.herokuapp.com/`

**Comment by smikulcik** [comment]
Oh perfect! I’ll push an update tomorrow. Thanks

**Comment by jaysonesmith** [comment]
Nice work and thank you!

**Pull request merged**
