### PR TITLE
Added gherkin verification of the pretty formatter

### PR DESCRIPTION
**Pull request by lonnblad**

### CODE REVIEW

**Comment by lonnblad** [comment]
We should probably remove the fixtures I added for JUnit and Cucumber and focus on more `features/formatter/<formatter>.feature`

**Comment by jaysonesmith** [comment]
@lonnblad Why do you say we should remove them? Are they not providing any value currently?

**Comment by lonnblad** [comment]
I believe they provide som value, but we can run them with less feature files, just to verify that the concurrency works and with that at least have much smaller fixtures.

The main verification of the formatters would be done like we already do in `features/formatter/cucumber.feature` and what I know did with the `features/formatter/junit.feature`.

**Comment by jaysonesmith** [comment]
That sounds good. I'll trust your judgement!

**Pull request merged**
