### PR TITLE
update gherkin-go to v19.0.3

### PR DESCRIPTION
**Pull request by mbow**
update messages-go to v16.0.1
bump gomod version
comment on log line in std os.Stderr
examples to non rc version
go mod tidy
update circle (tbd)

# Description

fixes for https://github.com/cucumber/godog/pull/390
this branch is to fix panics on an update of library versions due to getter methods being removed and default values are nil.

	"github.com/cucumber/gherkin-go/v19"
	"github.com/cucumber/messages-go/v16"

If it fixes an open issue https://github.com/cucumber/godog/issues/396

this should close a CVE in the above lib and allow use in orgs that scan for CVE's

## Type of change

- Refactoring

# Checklist:

- [X] My code follows the code style of this project.
- [-] My change requires a change to the documentation.
- [-] I have updated the documentation accordingly.
- [-] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [-] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by mbow** [comment]
@mattwynne c this should fix the issues found on the other branch.

**Comment by aslakhellesoy** [comment]
Great work @mbow!

This looks good to me, and if you think it's ready to merge I'll do it @mbow.

We're discussing a merge of godog/gobdd over in the #committers-go channel in the [Cucumber slack](https://cucumberbdd-slack-invite.herokuapp.com/) - any chance you could join the discussion there?

**Comment by Yellaks** [comment]
@mbow - this looks good to me :)

**Comment by mbow** [comment]
@aslakhellesoy think the circle builds need to be triggered as maybe that change won't work ( new default images for circle and took a quick guess )

**Comment by mattwynne** [comment]
I don't understand why CircleCI is not building this branch. I'm going to merge it anyway, and if there are any problems with the build hopefully we can just sort them out in the main branch, once you have the commit bit @mbow. Thanks a lot!

**Comment by aslakhellesoy** [comment]
Hi @mbow,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
