### PR TITLE
Update go version in go.mod (go1.16). Update dependencies.

### PR DESCRIPTION
**Pull request by mdeolmosmeli**
### 🤔 What's changed?

Fix go version in go mod and update dependencies.

### ⚡️ What's your motivation? 

Stop using old dependencies.

There are some old dependencies in the code. Updating them, I found that go version is 1.13 in go mod. 👉  [(Here)](https://github.com/cucumber/godog/blob/main/go.mod#L3)
But when I run the test I was asked to use go 1.17 👉 [Here](https://github.com/cucumber/godog/blob/main/Makefile#L6)

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Comment by mdeolmosmeli** [comment]
Hi @aslakhellesoy. 
Some workflow checks keep waiting for hours
image

Do you know why?

Sorry to bothering you, I saw that you made changes recently so I though you may be know

Regards,
Martin

**Comment by aslakhellesoy** [comment]
No idea - I haven’t made any significant commits to this repo. Maybe some of rhe regular contributors can answer.

**Comment by mdeolmosmeli** [comment]
> Hi @aslakhellesoy. Some workflow checks keep waiting for hours image
> 
> Do you know why?
> 
> Sorry to bothering you, I saw that you made changes recently so I thought you may be know
> 
> Regards, Martin

@vearutop/@mattwynne Do you what could be wrong?

**Comment by vearutop** [comment]
Hi @mdeolmosmeli, these actions are not started automatically for first-time contributors due to security concerns, they are only started once another contributor approves them to run. 

I have just approved CI run, however it failed with 
```
 	github.com/hashicorp/go-memdb@v1.3.2: missing go.sum entry; to add it:
	go mod download github.com/hashicorp/go-memdb
```

I think you need to `cd _examples; go mod tidy` to fix that.

**Pull request closed without merging**
