### PR TITLE
368 public formatter

### LINKED ISSUE #368: Make Base Formatter public and/or accessible by custom formatters
**Is your feature request related to a problem? Please describe.**
When writing a custom formatter, the entire formatter logic must be rewritten because the base formatter is public, but within the `internal` folder

**Describe the solution you'd like**
Make the Base Formatter available to use by those writing custom formatters. Perhaps keep the base formatter within the internal structure, but add a `CustomFormatterBase` struct at the root level that can be referenced.

### PR DESCRIPTION
**Pull request by leviable**
Closes #368 

This PR exposes Godog formatters, making them embeddable by custom formatters

- [x]  My code follows the code style of this project.
- [x]  My change requires a change to the documentation.
- [ ]  I have updated the documentation accordingly.
- [x]  I have read the CONTRIBUTING document.
- [x]  I have added tests to cover my changes.
- [x]  All new and existing tests passed.

### CODE REVIEW

**Comment by leviable** [comment]
If this is a non-starter, please let me know :)

**Comment by inluxc** [comment]
Is this issue still in progress?

**Comment by mattwynne** [comment]
Hi,

I'm one of the Cucumber org's maintainers. We're [short on regular maintainers for godog](https://github.com/cucumber/godog/issues/406) at the moment so sorry for the delay getting this reviewed. I'm happy to merge this if someone can rebase it.

**Comment by inluxc** [comment]
I will give it a try and test with one of my own formatters

**Review by vearutop — COMMENTED** [review]
I expressed my review suggestions as https://github.com/cucumber/godog/pull/418, please check if they make sense to be applied here.

**Review by vearutop — APPROVED** [review]

**Pull request merged**
