### PR TITLE
Update api.go

### PR DESCRIPTION
**Pull request by xiaobudongzhang**
close db this connection every time, so can restore db data

### CODE REVIEW

**Comment by vearutop** [comment]
Hi @xiaobudongzhang, could you tell a bit more about your change? It is not clear why should db connection be closed in http handler (not in `main()`).

**Comment by xiaobudongzhang** [comment]
> Hi @xiaobudongzhang, could you tell a bit more about your change? It is not clear why should db connection be closed in http handler (not in `main()`).

Because if db connection don't close, then db data will not rollback, test case will fail. This is my screenshot when db not [close.](https://raw.githubusercontent.com/xiaobudongzhang/adminer/master/F77763F0-8674-46fb-889F-F75ADDDAD65D.png)

**Comment by inluxc** [comment]
@xiaobudongzhang can you update to the latest branch?

Thanks in advance.

**Comment by xiaobudongzhang** [comment]
> @xiaobudongzhang can you update to the latest branch?
> 
> Thanks in advance.

i have update to lastest branch

**Comment by mattwynne** [comment]
@xiaobudongzhang did you try putting the `db.close()` call in the `main` function? It seems like if we put it here in the HTTP handler, the server will only be able to respond to a single request to the `/users` endpoint, and any subsequent requests would fail because the database connection will be closed. Surely the database connection should be closed when the server is stopped?

**Comment by xiaobudongzhang** [comment]
> @xiaobudongzhang did you try putting the `db.close()` call in the `main` function? It seems like if we put it here in the HTTP handler, the server will only be able to respond to a single request to the `/users` endpoint, and any subsequent requests would fail because the database connection will be closed. Surely the database connection should be closed when the server is stopped?

yes i close db in wrong place, thanks , i have close db in  api_test.go . in api_test.go close db after  get /users

**Comment by xiaobudongzhang** [comment]
this is not close db sql:
`
211202 18:15:47	    82 Connect	root@localhost on godog_test using TCP/IP
		    82 Query	START TRANSACTION
		    82 Query	SELECT id, email, username FROM users
		    82 Prepare	INSERT INTO users (username, email) VALUES(?, ?)
		    82 Execute	INSERT INTO users (username, email) VALUES('john', 'john.doe@mail.com')
		    82 Execute	INSERT INTO users (username, email) VALUES('jane', 'jane.doe@mail.com')
		    82 Query	SELECT id, email, username FROM users
		    82 Prepare	INSERT INTO users (username, email) VALUES(?, ?)
		    82 Execute	INSERT INTO users (username, email) VALUES('gopher', 'gopher@mail.com')
		    82 Query	SELECT id, email, username FROM users
`

this is close db sql:
`
211202 18:15:56	    83 Connect	root@localhost on godog_test using TCP/IP
		    83 Query	START TRANSACTION
		    83 Query	SELECT id, email, username FROM users
		    83 Query	ROLLBACK
		    83 Query	START TRANSACTION
		    83 Prepare	INSERT INTO users (username, email) VALUES(?, ?)
		    83 Execute	INSERT INTO users (username, email) VALUES('john', 'john.doe@mail.com')
		    83 Execute	INSERT INTO users (username, email) VALUES('jane', 'jane.doe@mail.com')
		    83 Query	SELECT id, email, username FROM users
		    83 Close stmt	
		    83 Query	ROLLBACK
		    83 Query	START TRANSACTION
		    83 Prepare	INSERT INTO users (username, email) VALUES(?, ?)
		    83 Execute	INSERT INTO users (username, email) VALUES('gopher', 'gopher@mail.com')
		    83 Query	SELECT id, email, username FROM users
		    83 Close stmt	
		    83 Query	ROLLBACK
`

**Pull request closed without merging**
