### PR TITLE
Add new contextualized API for hooks and steps

### LINKED ISSUE #88: hooks return error
Currently the return values of hooks is not used. I'd like to be able to return an error in BeforeScenario/AfterScenario (and the other steps) and have it printed as as error instead of having to panic as my current workaround

### LINKED ISSUE #175: Pass the feature's name to a step
Hi @l3pp4rd!

Is there a way to pass the current scenario/feature definition to a step? I would like to log each HTTP requests that we send to our API and I need to attach the current feature name and scenario name. I was thinking to use the hooks somehow but I think if I run the tests parallel that couldn't work.

### LINKED ISSUE #360: Adding context to steps
**Is your feature request related to a problem? Please describe.**
We want to generate a library with some common steps. For example, a step that sends a REST request, a step that checks the status code, a step that validates the response, and a step that checks a HTTP header from the response. In this way, we could reuse some common steps.
However, godog only passes the regex parameters as arguments. We could use a `struct` and create methods for that type. But we wouldn't get reusable steps in any scenario.

**Describe the solution you'd like**
I'd like that each scenario creates a `context.Context` instance (or custom context) and the context is passed as first argument in each step function. Instead of:
```
func thereAreGodogs(available int) error {
```
we would have:
```
func thereAreGodogs(context.Context ctx, available int) error {
```
Note that `context.Context` is immutable. So we would need to create a map to store all context changes related to godog, to return the context to chain the context for the next step, or to use a custom context type.

**Describe alternatives you've considered**
We could use InitializeScenario for this purpose but it would require a lot of repetitive code for each step:
```
func InitializeScenario(ctx *godog.ScenarioContext) {
	var stepCtx godog.Context
	ctx.Step(`^there are (\d+) godogs$`, func(available int) {
		thereAreGodogs(stepCtx, available)
	})
	...
}
```

**Additional context**
See [GoBDD](https://github.com/go-bdd/gobdd) that follows this approach. See also the [motivations to write an alternative to Godog](https://go-bdd.github.io/gobdd/) which I consider to be very good feedback for possible improvements in Godog.

### LINKED ISSUE #370: ScenarioContext.AfterStep not invoked after a failed case
### What version of godog are you using?
Godog version is: v0.11.0

### What version of Go are you using?
go version go1.15.1 darwin/amd64

### What did you do?
I enabled the hooks BeforeStep and AfterStep on godog.ScenarioContext to output som logs after each step, and it worked just fine, until one step failed. After the step failed the BeforeStep was invoked but not the AfterStep.

### What did you expect to see?
Either both the AfterStep and BeforeStep is invoked on following steps after a failed step or both AfterStep and BeforeStep is **not** invoked after a failed step.

### What did you see instead?
BeforeStep was invoked for every step after a failed step, but not the AfterStep.

### LINKED ISSUE #378: Unable to get TestStepResult from AfterStep
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
v0.11.0
```

### What version of Go are you using?
```
go1.16 
```

### What did you do?
I'm trying to get the TestStepFinished.TestStepResult.Status for each step, from an AfterStep func.
By doing the below within the InitializeScenario.

```
func InitializeScenario(s *godog.ScenarioContext) {

    s.AfterStep(func(st *messages.TestStepFinished, err error) {
		    stepResultStatus = st.TestStepResult.Status
	    })
```

### What did you expect to see?

I expected the AfterStep method to compile, and a possible status from the below to be returned on execution.
```
	TestStepResult_UNKNOWN TestStepResult_Status = 0
	TestStepResult_PASSED TestStepResult_Status = 1
	TestStepResult_SKIPPED TestStepResult_Status = 2
```

### What did you see instead?
The AfterStep doesn't compile and returns the below error.
```
Cannot use 'func(st *messages.TestStepFinished, err error) { resultStatus = st.TestStepResult.Status }' (type func(st *messages.TestStepFinished, err error)) as type func(st *Step, err error)
```

Not sure how to obtain values like TestStepFinished and also GherkinDocument_Feature_Step?

### LINKED ISSUE #397: Support per-scenario data shared across steps
**Is your feature request related to a problem? Please describe.**
Sharing data among steps while ensuring each scenario has its own set of data is difficult.

**Describe the solution you'd like**
I would like to be able to share data across steps and ensure that each scenario has its own copy.

**Describe alternatives you've considered**
Currently, I'm using file-level `var`s and initializing them with `ctx.BeforeScenario`. Some of the `var`s are initialized in a `Given` step since their initialization depend on argument values passed into the step.

Since each scenario will be using the same file-level `var`, this implies they won't be able to be run concurrently.

### PR DESCRIPTION
**Pull request by vearutop**
# Description

This PR introduces new API for hooks and steps that includes context and errors. 

# Motivation & context

In order to grant more control to test suite user, we can upgrade the API for hooks and steps.
This PR implements new API suggested in https://github.com/cucumber/godog/issues/360#issuecomment-882849699.

```go
type ScenarioContext struct {
	suite *suite
}

// StepContext allows registering step hooks.
type StepContext struct {
	suite *suite
}

// Before registers a hook to invoke before scenario.
func (ctx ScenarioContext) Before(h BeforeScenarioHook) {
	ctx.suite.beforeScenarioHandlers = append(ctx.suite.beforeScenarioHandlers, h)
}

// BeforeScenarioHook defines a hook before scenario.
type BeforeScenarioHook func(ctx context.Context, sc *Scenario) (context.Context, error)

// After registers a hook to invoke after scenario.
func (ctx ScenarioContext) After(h AfterScenarioHook) {
	ctx.suite.afterScenarioHandlers = append(ctx.suite.afterScenarioHandlers, h)
}

// AfterScenarioHook defines a hook after scenario.
type AfterScenarioHook func(ctx context.Context, sc *Scenario, err error) (context.Context, error)

// StepContext exposes StepContext of a scenario.
func (ctx *ScenarioContext) StepContext() StepContext {
	return StepContext{suite: ctx.suite}
}

// Before registers a hook to invoke before step.
func (ctx StepContext) Before(h BeforeStepHook) {
	ctx.suite.beforeStepHandlers = append(ctx.suite.beforeStepHandlers, h)
}

// BeforeStepHook defines a hook before step.
type BeforeStepHook func(ctx context.Context, st *Step) (context.Context, error)

// After registers a hook to invoke after step.
func (ctx StepContext) After(h AfterStepHook) {
	ctx.suite.afterStepHandlers = append(ctx.suite.afterStepHandlers, h)
}

// AfterStepHook defines a hook after step.
type AfterStepHook func(ctx context.Context, st *Step, err error) (context.Context, error)
```

Original API is left for backwards compatibility with deprecation comments.

Step definitions now optionally support having `ctx context.Context` as a first argument.

Step definition may have one of the following returns processed with help of reflection:
* empty (nothing returned)
* `context.Context` - newly added
* `error`
* `(context.Context, error)` - newly added

```go
func thereAreGodogs(context.Context ctx, available int) (context.Context, error) {
```

The context is chained though all hooks and steps allowing pass state of earlier actions to later ones.

Resolves #360.
Resolves #88.
Resolves #175 with ability to inject Scenario specific data to context and read it back from Step hook.
Resolves #397.
Resolves #370.
Resolves #378.

## Type of change

- New feature (non-breaking change which adds new behaviour)

## Note to other contributors

No note.

## Update required of cucumber.io/docs

Not sure.

# Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by priyankshah217** [comment]
@vearutop can you include an example of sharing data across step definitions?

**Comment by vearutop** [comment]
@priyankshah217 please check this example

https://play.golang.org/p/lSnIIlf4Puw

```feature
Feature: Passing state
  Scenario: Passing state between steps
    # Saving state of total number of godogs
    Given I have a random number of godogs

    # Reading state to eat total number of godogs
    When I eat all available godogs

    Then there are no godogs left
```

```go
package main

import (
	"context"
	"errors"
	"io/ioutil"
	"log"
	"math/rand"
	"os"

	"github.com/cucumber/godog"
)

type godogEater struct{ cnt uint32 }

func (ge *godogEater) Add(cnt uint32)    { ge.cnt += cnt }
func (ge *godogEater) Available() uint32 { return ge.cnt }
func (ge *godogEater) Eat(cnt uint32) error {
	if cnt > ge.cnt {
		return errors.New("can't eat more than I have")
	}
	ge.cnt -= cnt
	return nil
}

type cntCtxKey struct{} // Key for a particular context value.

func main() {
	if err := ioutil.WriteFile("/tmp/state.feature", []byte(`
Feature: Passing state
  Scenario: Passing state between steps
    Given I have a random number of godogs

    When I eat all available godogs

    Then there are no godogs left
`), 0600); err != nil {
		log.Fatal(err)
	}
	defer os.Remove("/tmp/state.feature")

	eater := godogEater{}

	suite := godog.TestSuite{
		ScenarioInitializer: func(s *godog.ScenarioContext) {
			// Creating a random number of godog and storing it in context for future reference.
			s.Step("I have a random number of godogs", func(ctx context.Context) context.Context {
				cnt := rand.Uint32()
				println("adding random godogs", cnt)
				eater.Add(cnt)
				return context.WithValue(ctx, cntCtxKey{}, cnt)
			})

			// Getting previously stored number of godogs from context.
			s.Step("I eat all available godogs", func(ctx context.Context) error {
				cnt := ctx.Value(cntCtxKey{}).(uint32)
				println("eating random godogs", cnt)
				return eater.Eat(cnt)
			})

			s.Step("there are no godogs left", func() error {
				if eater.Available() != 0 {
					return errors.New("there are still a few godogs")
				}
				return nil
			})
		},
		Options: &godog.Options{
			Format:   "pretty",
			Strict:   true,
			NoColors: true,
			Paths:    []string{"/tmp/state.feature"},
		},
	}

	if suite.Run() != 0 {
		log.Fatal("non-zero status returned, failed to run feature tests")
	}
}
```

**Comment by priyankshah217** [comment]
@vearutop thanks for your help.

**Review by inluxc — APPROVED** [review]

**Comment by zhammer** [comment]
hey hey this closed out two issues i was following on this repo. not using godog currently but thanks for the work :)

**Comment by priyankshah217** [comment]
@vearutop I need some help, I was trying ur example and it worked fine. But have a question related to what if step def contains some parameters and how can we pass context (refer below example)? would you please give me some examples?

`s.Step("I have a (\d+) number of godogs", iHaveANumberOfGoDogs)`

**Comment by vearutop** [comment]
You can add context as a first argument to any step definition, so if you have one numeric argument, you can declare step as `func(ctx context.Context, cnt int) context.Context`, for example:

```go
			// Creating a random number of godog and storing it in context for future reference.
			s.Step("I have a (\d+) number of godogs", func(ctx context.Context, cnt int) context.Context {
				println("adding godogs", cnt)
				eater.Add(cnt)
				return context.WithValue(ctx, cntCtxKey{}, cnt)
			})
```

Please also check examples in release notes: https://github.com/cucumber/godog/blob/main/release-notes/v0.12.0.md#step-definition-improvements.

**Pull request merged**
