### PR TITLE
Rename examples to _examples

### PR DESCRIPTION
**Pull request by axw**
Rename the examples directory so that the examples' dependencies don't leak into the main module.

### CODE REVIEW

**Comment by jaysonesmith** [comment]
Hi and welcome @axw! Thanks for the help with this.

**Comment by axw** [comment]
@jaysonesmith no problem, updated.

**Comment by jaysonesmith** [comment]
Thank you! That's helped me realize we're using the wrong link format and likely my fault. :p

**Comment by aslakhellesoy** [comment]
Hi @axw,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by jaysonesmith** [comment]
Also, @axw : In the Changelog, the brackets around usernames is used to help link to folk's GH pages, but needs a corresponding link to do so. If you look at the end of the changelog file, you'll see what I mean. I'm working on an update to the file now that'll include you, so don't worry about doing it. :)

**Comment by axw** [comment]
@jaysonesmith ugh, sorry - I should have checked the output. Thank you.

**Comment by jaysonesmith** [comment]
@axw No worries!

**Pull request merged**
